# Don't change anything in here
win32: VERSION = $${MAJOR_VER}.$${MINOR_VER}.$${PATCH_VER}.$${BUILD_VER}
else: VERSION = $${SMALL_VERSION}

SMALL_VERSION = $${MAJOR_VER}.$${MINOR_VER}.$${PATCH_VER}

VER_MAJ = $${MAJOR_VER}
VER_MIN = $${MINOR_VER}
VER_PAT = $${PATCH_VER}

DEFINES += QM_MAJOR_VERSION=$$MAJOR_VER
DEFINES += QM_MINOR_VERSION=$$MINOR_VER
DEFINES += QM_PATCH_VERSION=$$PATCH_VER
DEFINES += QM_BUILD_VERSION=$$BUILD_VER
